### ISSUE TITLE
Combine erosion and dilation code because of the property erode(x) = -dilate(-x)

### ISSUE THREAD

**Issue by Manza12** [Manza12/nnMorpho#5]
Also perhaps erosion and dilation code can be combined? since `erode(x) == -dilate(-x)` and vice versa.

_Originally posted by @s-rog in https://github.com/Manza12/nnMorpho/issues/3#issuecomment-830984514_

**Comment by Manza12** [comment]
The problem with that is that we loose computation speed doing that:

- We apply two minus operators, which increases the computation time (x2)
- But the greatest problem is that the formula is not exactly this one; it is `erode_{b}(x) = -dilate_{R[b]}(-x)` where `R` stands for the reflection operator. The reflection operator in PyTorch is torch.flip, and can be used in view mode, but increases considerably the computation time (x1000)

Check the module [test_combination_erosion_dilation.py](https://github.com/Manza12/nnMorpho/blob/main/tests/test_combination_erosion_dilation.py) for the computations.

**Comment by s-rog** [comment]
Ah I see, in that case the current implementation is probably best!

**Comment by Manza12** [comment]
However, I will combine the Python code since it is almost duplicated... (I was referring to the CUDA code before)
