### ISSUE TITLE
Functions apply doesn't get the proper gradients when working with batched images

### ISSUE THREAD

**Issue by Manza12** [Manza12/nnMorpho#8]
I don't know why this is happening but I don't get the proper gradients. I will work on this first for the new release

**Comment by s-rog** [comment]
Does 1.1.1 fix this issue? or are these different gradient problems?

**Comment by Manza12** [comment]
This are different gradient problems. I wanted to make this release for being the library being working properly as soon as possible.
I will work on the other gradient problems right now and make a new release.
